[스택, 큐, 덱] 8월 30일
Altu-Bitu-5/Altu-Bitu-LeeSomin pull request #2
Opened 2023-08-30 07:47 UTC by shl4869

###인적사항
학번: 2071035
이름: 이소민
</br>

###과제제출
기존제출: 1431, 14425, 19636
추가제출:
</br>

2023-09-01 08:09 UTC, Goldchae approved these changes
p3. 변수는 스네이크형으로 작성해주세요! 코드 로직 깔끔하게 잘 짜신 것 같습니다! 수고하셨어요.

2023-09-01 08:09 UTC, Goldchae commented on 02_스택, 큐, 덱/1158.cpp
> +		// a가 k의 배수이면 큐의 맨 앞 원소를 결과 벡터에 저장
주석 달아주신 것 좋습니다!

2023-09-01 08:09 UTC, Goldchae commented on 02_스택, 큐, 덱/1158.cpp
> +	queue <int> yosequeue;
p3. 변수명은 가독성이 좋게 스네이크형으로 작성해주세요! ex) yose_queue

2023-09-01 08:09 UTC, Goldchae commented on 02_스택, 큐, 덱/1158.cpp
> +		if (j==result.size()-1) {
p3. 조건문 없이 맨 마지막에 > 출력문 한 줄만 넣어도 좋을 것 같습니다!

2023-09-01 08:09 UTC, Goldchae commented on 02_스택, 큐, 덱/4949.cpp
> +string isBalanced(string str) {
함수 나눠주신 것 좋습니다!

2023-09-01 08:09 UTC, Goldchae commented on 02_스택, 큐, 덱/4949.cpp
> +	vector <string> strvec;
이 변수명도 str_vec이 좋을 것 같습니다!

2023-09-01 14:26 UTC, chae-jpg requested changes
[스택, 큐, 덱 구현 코드 리뷰 완료]

10757(P1)

안녕하세요 소민님! 코드 리뷰 완료되었습니다👍
주석도 잘 달아주시고, 덧셈과 스택의 성질을 이용해서 문제도 잘 풀어주셨지만, 몇 가지 문제점 때문에 현재 백준에서 오답으로 판정되고 있습니다😢
알튜비튜에서는 백준에서 정답으로 인정되는 코드만을 제출로 인정하기 때문에, 드린 몇 가지 코멘트 보시고 수정 부탁드려요!
궁금한 점이 있으시다면 리뷰어를 호출해주세요~

2023-09-01 14:26 UTC, chae-jpg commented on 02_스택, 큐, 덱/10757.cpp
> +string addBigNum(string a, string b) {
함수 분리 좋습니다!

2023-09-01 14:26 UTC, chae-jpg commented on 02_스택, 큐, 덱/10757.cpp
> +		}
P1
이 부분에서 stack에 char을 int로 변환하는 과정과, carrry를 구하고 더하는 과정이 빠져 있어서 현재 백준에서 통과가 되지 않습니다😢 수정 부탁드립니다!

2023-09-01 14:26 UTC, chae-jpg commented on 02_스택, 큐, 덱/10757.cpp
> +	result.push_back('\0');
P1
이 부분도, '\0'이 문자열의 마지막을 나타내는 데 필요하지 않습니다! 위 부분 수정하시고, 이 부분까지 제거하시면 바로 정답으로 처리될 거예요👍

2023-09-18 02:29 UTC, chae-jpg commented
안녕하세요 소민님! 답변 늦어진 점 정말 죄송합니다😥 알림이 오지 않아서 확인에 시간이 걸렸습니다😓
수정해주신 코드 확인해본 결과, 그대로 머지하셔도 좋을 것 같습니다! 다시 한 번 죄송하다는 말씀 드리고, 수정하시느라 수고 많으셨습니다!👍

2023-09-18 02:31 UTC, chae-jpg approved these changes
안녕하세요 소민님! 답변 늦어진 점 정말 죄송합니다😥 알림이 오지 않아서 확인에 시간이 걸렸습니다😓
수정해주신 코드 확인해본 결과, 그대로 머지하셔도 좋을 것 같습니다! 다시 한 번 죄송하다는 말씀 드리고, 수정하시느라 수고 많으셨습니다!👍

2023-09-18 14:40 UTC, merged